# Generated by Django 3.1.7 on 2021-08-03 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth_api', '0002_alter_userrecord_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='userrecord',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
