# Generated by Django 3.2 on 2021-06-10 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acom_type', models.CharField(choices=[('PASS', 'Passage'), ('DIG', 'Diagram')], max_length=100)),
                ('passage', models.TextField(null=True)),
                ('diagram', models.ImageField(default=None, null=True, upload_to='media/images/')),
                ('subject', models.CharField(choices=[('ENG', 'English'), ('MATH', 'Mathematics'), ('PHY', 'Physics'), ('GEO', 'Geography'), ('BIO', 'Biology')], default='English', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('option_A', models.TextField()),
                ('option_B', models.TextField()),
                ('option_C', models.TextField()),
                ('option_D', models.TextField()),
                ('option_E', models.TextField(null=True)),
                ('correct_ans', models.TextField()),
                ('explain', models.TextField(null=True)),
                ('subject', models.CharField(choices=[('ENG', 'English'), ('MATH', 'Mathematics'), ('PHY', 'Physics'), ('GEO', 'Geography'), ('BIO', 'Biology')], max_length=100)),
                ('year', models.IntegerField(choices=[('1990', 1990), ('1991', 1991), ('1992', 1992), ('1993', 1993), ('1994', 1994), ('1995', 1995), ('1996', 1996), ('1997', 1997), ('1998', 1998), ('1999', 1999), ('2000', 2000), ('2001', 2001), ('2002', 2002), ('2003', 2003), ('2004', 2004), ('2005', 2005), ('2006', 2006), ('2007', 2007), ('2008', 2008), ('2009', 2009), ('2010', 2010), ('2011', 2011), ('2012', 2012), ('2013', 2013), ('2014', 2014), ('2015', 2015), ('2016', 2016), ('2017', 2017), ('2018', 2018), ('2019', 2019), ('2020', 2020), ('2021', 2021)])),
                ('acom_type', models.CharField(choices=[('PASS', 'Passage'), ('DIG', 'Diagram')], max_length=100, null=True)),
                ('exam_type', models.CharField(choices=[('UTME', 'Jamb Examination'), ('POST-UTME', 'Post Jamb Examination')], max_length=100, null=True)),
                ('accompany', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='questions_api.accompany')),
            ],
        ),
    ]
