# Generated by Django 2.2.16 on 2021-03-17 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mockexamsapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accompany',
            name='diagram',
            field=models.ImageField(default=None, null=True, upload_to='media/images/'),
        ),
        migrations.AlterField(
            model_name='accompany',
            name='passage',
            field=models.TextField(null=True),
        ),
    ]
