# Generated by Django 2.2.16 on 2021-03-23 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mockexamsapp', '0004_auto_20210318_2336'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='exam_type',
            field=models.CharField(choices=[('UTME', 'Jamb Examination'), ('POST-UTME', 'Post Jamb Examination')], max_length=100, null=True),
        ),
    ]
