# Generated by Django 3.2 on 2021-06-03 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mockexamsapp', '0005_question_exam_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='accompany',
            name='subject',
            field=models.CharField(choices=[('ENG', 'English'), ('MATH', 'Mathematics'), ('PHY', 'Physics'), ('GEO', 'Geography'), ('BIO', 'Biology')], default='English', max_length=100),
        ),
    ]
